www/website-content/pages/documentation/introduction/building-haxe.md
Apparently they are now packaged separately, at least within homebrew.
=> Add installation of Camlp4 for Mac

www/css/style.css
I think for design reasons the links in headers aren't blue. But I think it would make sense to give in indication what is clickable.
=> Underlines to links in headers

www/website-content/pages/foundation/open-source.md
Maybe this link would be better located in a "Contribute" page, but I didn't find it so far.
=> Added a link to haxe compiler source code

www/website-content/pages/use-cases/web/index.html
the ufront link was dead, redirecting to github repo
=> Fixing ufront dead link

www/img/haxe-logo-horizontal-on-dark.svg, www/img/haxe-logo.svg
I really dislike that ugly glitchy dark line on the logo on the website. I think its a browser rendering issue because in the original svg all paths look connected. I gave the lower triangles an extra anchor point an moved that a bit inside. So its not a perfect path anymore, but fixes the view on small sizes. 
I did not change colors, I did use an svg-optimizer since Illustrator adds some bloat to svg files.
=> Update haxe-logo 

www/website-content/pages/documentation/introduction/toolkit-introduction.md, www/website-content/pages/index.html, www/website-content/sitemap.json
* Navigate to "Compiler usage" on manual page instead of "introduction" section
* Moved it to bottom of navigation too. In the end this whole section should be part of the manual but for time being this is decent solution?
* Changed "compiler-reference" link on homepage to "compiler-features", since we don't have a compiler reference page written.
=> Compiler usage links

www/website-content/pages/documentation/introduction/building-haxe.md
Adds a simple instruction list to the page for compiling haxe from source on FreeBSD.
=> Add build instructions for FreeBSD

www/website-content/sitemap.json
I think the navigation is the only place where "Haxelib" was camel-cased.
=> HaxeLib -> Haxelib

www/website-content/pages/documentation/introduction/compiler-targets.md
As a newcomer, you might think typing is not always available when quickly looking at this table.
=> Make it clear that Haxe itself is typed

pages/download/linux/index.html
The debian install guide tells the user to add the following line
deb http://httpredir.debian.org/debian unstable main contrib non-free
to `/etc/apt/sources.list`
`contrib` and `non-free` are as far as I know not necessary for haxe to work, besides not being opensource.
=> Remove unnecessary sections

www/css/haxe-nav.css
How to reproduce : 
1. go to haxe.org
2. resize the window size to anything above 980 width
3. try to click the haxe logo in top left corner
Search bar is _sometimes_ not clickable when the width is around ~1200px.
The css z-index changes in this PR fix this.
=> Fixes search and haxe logo in navbar being unclickable at certain sizes

.codeclimate.yml, .editorconfig, checkstyle.json
- disable markdownlint 
more than 3400 issues; complaining about line length, header style, trailing whitespace, etc.
Unless someone volunteers, these issues will remain indefinitely.
Alternative approach would be to disable individual markdownlint checks, though it's unclear how many checks would remain active.
- disable csslint
more than 1500 issues; most of them from external files like `bootstrap.min.css`
It's unlikely that external files will ever pass a csslint check, unless their owners make an effort to do so. 
Which leaves over 400 issues in `style.css`, waiting for a volunteer...
- added editorconfig file
should help with trailing whitespace and indentation character issues for future edits (when using an editor with editorconfig support)
- added some excludes to checkstyle
not …
=> reduce number of codeclimate issues

src/DownloadsData.hx
On pull requests, we call github API without a token and quickly get a rate limit error.
When that happens, we get an error object instead of an array of github releases, which is not catched by the code and breaks almost every CI runs on PRs.
This PR does two things:
* detect failed github API calls and fallback to `[]` for github releases
* when on a PR, trace a warning and fallback to an empty assets (download links) array instead of crashing
Example job hitting github API rate limit and not failing: https://travis-ci.org/HaxeFoundation/haxe.org/jobs/534270733
Note on the PR detection, from [travis docs](https://docs.travis-ci.com/user/environment-variables/):
>`TRAVIS_PULL_REQUEST` is set to the pull request number if the current job is a pull request build, or `false` if it’s not.
=> Fix CI on pull requests

videos/conferences/10.accu-2019.json, videos/conferences/8.haxeup-session-jan-2019-luxembourg.json
The only part that's perhaps a bit strange is that this is now listed under "Haxe conferences", when it's really just a non-Haxe-conference that happens to have had a talk about Haxe.
Not sure if that warrants creating a whole new category though... Or maybe "Haxe Conferences" could just be changed to "Conferences".
=> Add the ACCU 2019 talk to the videos section

pages/documentation/introduction/index.html, pages/documentation/platforms/csharp.html, pages/documentation/platforms/java.html, pages/documentation/platforms/javascript.html, pages/documentation/platforms/nodejs.html, pages/documentation/platforms/php.html, pages/documentation/platforms/python.html
- fix typos, mistakes, step numbering
- make individual guides generally use the same wording for consistency
- use `pre` for code snippets
=> Improvements to platform introductions

pages/documentation/introduction/compiler-targets.md
Though I haven't used this target, I noticed in the "What's new in 4.0" doc that JVM is now here.
=> Added JVM bytecode to compiler-targets doc

.gitmodules, .travis.yml, README.md, src/generators/Manual.hx
Closes https://github.com/HaxeFoundation/HaxeManual/issues/424
This PR changes how the manual is deployed. It is no longer a submodule, which means it does not need to be updated in this repo manually. Instead, any Travis build will use the latest available commit on the master branch of `HaxeManual`.
For local development, `manual` needs to be a directory created either by cloning the `HaxeManual` repo, or by symlinking to an existing repo containing the manual. The `Manual.hx` generator [warns](https://github.com/HaxeFoundation/haxe.org/pull/414/files#diff-ab717cfe57cd8d33adb019f6f2b94069R60-R64) when the `manual` directory doesn't exist.
=> Change manual deployment

pages/documentation/introduction/index.html
I'm not 100% sure, but with Haxe 4 existing for some time already and with it being mentioned on the front page and referenced many times in the docs, it looks like the version number should be updated here as well.
The generated API docs, from what I can see, were last made for 3.4.3 release and never again. It would be good to regenerate the docs zip for Haxe 4, or failing that, to remove the link altogether; for now, I just added version number to the link.
=> Update version numbers on documentation intro

pages/documentation/platforms/eval.html
The simplest and easiest option to get started writing and locally running Haxe code.
Modeled after the Python one.
See issue #401 .
=> Create eval.html getting started page

pages/use-cases/games/index.html
haxepunk.com seems to be taken over by a generic article spewing machine. Linking to github-repo instead.
=> Update link to Haxepunk

.travis.yml
The node dependencies we use are really old and do not work with modern versions of node, so we need to use version ~12~ 8.
Taken from: https://stackoverflow.com/questions/44249044/how-can-i-install-a-specific-node-js-version-on-a-php-container-on-travis-ci
=> Attempt to fix ci

src/DownloadsData.hx
Minor issue, but it's been bothering me for a few days...
Currently, it's:
This fixes it to be:
=> Fix order of windows downloads

pages/use-cases/mobile/index.html
Removed the mention of StablexUI from mobile use cases since it's abandoned for a long time.
=> Removed StablexUI from list of frameworks

Earthfile, README.md, package-lock.json, package.json, src/Main.hx, src/SyntaxHighlighter.hx
Update the highlighter library so we can finally stop depending on an ancient version of nodejs.
See: https://github.com/ibilon/Highlighter/pull/5
=> Update highlighter library

pages/use-cases/desktop/index.html
This is a minor pull request that removes Waxe's website from the list of suggested desktop UI libraries. Their website is offline and it doesn't seem to be actively maintained anymore.
=> Remove Waxe from the Desktop Apps page

www/css/haxe-nav.css
This css seems to be copied for the community.haxe.org page, but over there the open sans font hasn't been loaded like on haxe.org which results in the font being incorrect.
Other parts of the css in this repo do include this fallback, so it is a good idea anyway.
=> Add sans-serif as fall back for nav bar element
