www/website-content/pages/community/events.md
We should put this on the frontpage, too.
=> Add WWX 2015 announcement

www/website-content/pages/documentation/introduction/building-haxe.md
Shameless plug: Mentions the docker image created by me.
=> Add instructions for running unit tests.

www/website-content/pages/use-cases/web/index.html
Ref https://github.com/HaxeFoundation/haxe.org/issues/3
=> Remove classhomie app

www/website-content/pages/foundation/index.html
partner logo also on foundation page
=> Partner logo update

www/website-content/downloads/3.2.0-rc.2/RELEASE.md, www/website-content/downloads/3.2.0/RELEASE.md, www/website-content/pages/documentation/introduction/compiler-targets.md, www/website-content/pages/documentation/introduction/compiler-usage.md, www/website-content/pages/documentation/introduction/language-introduction.md, www/website-content/pages/use-cases/index.html
Same as https://github.com/HaxeFoundation/HaxeManual/pull/156
=> Javascript -> JavaScript, Actionscript -> ActionScript

www/website-content/pages/use-cases/mobile/index.html
See: https://github.com/HaxeFoundation/haxe.org/issues/139
=> Remove Basis from the list of frameworks for mobile

www/website-content/pages/documentation/introduction/editors-and-ides.html
https://atom.io/packages/language-haxe
=> Added Atom to editors, standardized platform order

www/website-content/pages/foundation/open-source.md
License headers are updated in https://github.com/HaxeFoundation/haxe/commit/ae6349cccff2149afade4babedefc90f3e5baa43
=> This is 2015 ;)

src/app/controller/DownloadController.hx, www/view/download/linux.html, www/view/download/version.html
=> Added info on the HF supported Linux packages.

README.md
=> Update the local copy instructions

src/app/view/error.html
Made a new error page by taking layout.html and baking in the navbar, sitemap and the current year.
Currently it's an old layout from 2013:
http://haxe.org/downld/
=> Use the latest layout for the page not found

www/view/layout.html
I just found out I forgot to add it. Expect many _likes_ after merging!
=> Add facebook to connect menu

src/app/model/SiteMap.hx
* closes https://github.com/HaxeFoundation/haxe.org/issues/185
* also fixes correct indentation.
=> fix footer links

www/website-content/pages/documentation/introduction/stdlib-introduction.md
Hi there,
I fixed to minor issues on the stdlib introduction page.
Cheers,
tpltnt
=> Stdlib typofix

src/BasicClient.hx, www/css/style.css
1. It highlights types (everything that starts with Capital)
2. the colors are slightly different
=> nicer looking code

www/css/style.css, www/website-content/pages/foundation/index.html, www/website-content/pages/index.html
I suspect the support plans are not very well known. We talked about them at wwx and many attendees didn't know what we're providing. So let's put it up there for a while :)
Feel free to suggest any revision to the wording.
=> Added back the notice banner to advertise the HF support plans.

Dockerfile
I think that should be safe but I know nothing about docker :)
allows to use a locally modified submodule which is easier to test when the bug is in ufblog.
cc @andyli
=> Use repo submodule in docker

www/website-content/pages/foundation/index.html, www/website-content/pages/foundation/partner.md
@ibilon @andyli @Simn **Don't push this to master yet, this is work in progress**
Initial setup partner/job page.
=> Add partner page

posts/2017-02-06-haxe-3.4-release.md
...but also link to the try.haxe snippet.
=> Still include the structInit snippet directly

posts/2017-03-12-zero-cost-abstracts.md
=> Zero-cost abstracts: some wording improvements

src/generators/Redirections.hx
Can be merged and pushed live when manual is exported.
=> redirect manual trace page to debugging section

pages/index.html
It had 3 spaces as indentation. The rest of the lines have 4.
=> Added missing space before var people in sample

pages/documentation/introduction/building-haxe.md
* pay attention to OCaml version in paths
* double check `make` is the one from OCaml32\bin (https://stackoverflow.com/questions/4002819/finding-the-path-of-the-program-that-will-execute-from-the-command-line-in-windo)
=> update Windows build instructions

pages/documentation/introduction/building-haxe.md
=> modify linux command line

pages/foundation/shop/index.html
+save location to locaStorage
+load us or eu shop by location
=> add location popin

pages/use-cases/who-uses-haxe.html
null-pointers are evil.
@markknol, do you think we can add a tooltip or something to show that the pages are no longer online?
=> Remove 404 links in "who uses haxe" page

videos/conferences/index.json
Was the only one here not using Title Case. ;)
Also noticed that the "upcoming event" description is outdated now.
=> Update conferences video section

videos/tutorials/4.kha-tutorial-series.json
new commit. should be better & fixed
=> Added follower/runner/creating libraries

pages/documentation/platforms/php.html
Revision #2 of the PHP Page
- Removed Tink
- Specified local PHP server not required
- Fixed note on PHP platform API
=> Add PHP Page

pages/documentation/platforms/php.html
@markknol Removed the haxe4 note per your comment.
=> Improve PHP page

pages/documentation/platforms/php.html
Fixes requested by Simn applied retroactively on PHP page.
=> PHP Page fixes

pages/documentation/platforms/csharp.html
Fixes requested by Simn applied retroactively on C# page.
=> C# page fixes

pages/documentation/platforms/java.html
Fix wording per @Simn and @RMax2015
=> Improve Java page

pages/documentation/platforms/csharp.html
Fix wording per @Simn and @RMax2015
=> Improve C# Page

pages/documentation/platforms/python.html
HXML fixes and add a compilation steps.
=> Improve Python page

views/MainLayout.html
Also wondering if "Chat" should default to Gitter, since Discord seems more active.
=> Fix GitHub spelling in "Connect"

pages/foundation/contact.html, views/MainLayout.html
=> Use the proper icon for Stack Overflow

videos/conferences/10.haxe-summit-us-2019.json
All videos are from [this playlist](https://www.youtube.com/playlist?list=PLU2M-shPcj1zZYoaApqDtbl64f1rIJnp5) which was made by cutting out separate videos from twitch streams of the conference
=> Add Haxe US Summit 2019 videos

videos/conferences/11.hkoscon-2019.json
All videos are cutted out from this stream of Hong Kong Open Source Conference 2019: https://www.youtube.com/watch?v=ATq8Y9gT6TY
=> Add Haxe related videos from HKOSCon 2019

pages/documentation/introduction/editors-and-ides.html
The project is abandoned and the links are broken
=> Remove HaxeDevelop from editors-and-ides.html

.travis.yml, README.md
Adds instructions for installing the required version of node to avoid errors while installing node modules.
=> Update readme build instructions

videos/conferences/16.haxein-2022-september.json
Unfortunately the quality of videos is low, but i think that it would be nice to have them anyway
=> Added links for HaxeIn 2022 videos
